ServerEvents.recipes(event => {
	event.recipes.gtceu.alloy_smelter('sourcestone')
		.itemInputs(Item.of('1x kubejs:source_gem_dust'))
		.itemInputs(Item.of('8x #forge:stone'))
		.itemOutputs(Item.of('8x ars_nouveau:sourcestone'))
		.duration(200)
		.EUt(8)	
	event.recipes.gtceu.alloy_smelter('blank_shard')
		.itemInputs(Item.of('1x create:andesite_alloy'))
		.itemInputs(Item.of('1x #forge:glass'))
		.itemOutputs(Item.of('1x kubejs:blank_shard'))
		.duration(100)
		.EUt(24)	
})
