ServerEvents.recipes(event => {
	event.recipes.gtceu.andesite_mechanical_drill('andesite')
		.notConsumable(Item.of('1x gtceu:andesite_alloy_drill_head'))
		.notConsumable(Item.of('1x minecraft:andesite'))
		.inputFluids(Fluid.of('gtceu:creosote',10))
		.itemOutputs('1x minecraft:andesite')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.andesite_mechanical_drill('iron_ore')
		.notConsumable(Item.of('1x gtceu:andesite_alloy_drill_head'))
		.notConsumable(Item.of('1x minecraft:raw_iron'))
		.inputFluids(Fluid.of('gtceu:creosote',10))
		.itemOutputs('1x minecraft:raw_iron')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.andesite_mechanical_drill('zinc_ore')
		.notConsumable(Item.of('1x gtceu:andesite_alloy_drill_head'))
		.notConsumable(Item.of('1x create:raw_zinc'))
		.inputFluids(Fluid.of('gtceu:creosote',10))
		.itemOutputs('1x create:raw_zinc')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.andesite_mechanical_drill('copper_ore')
		.notConsumable(Item.of('1x gtceu:andesite_alloy_drill_head'))
		.notConsumable(Item.of('1x minecraft:raw_copper'))
		.inputFluids(Fluid.of('gtceu:creosote',10))
		.itemOutputs('1x minecraft:raw_copper')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.andesite_mechanical_drill('coal_ore')
		.notConsumable(Item.of('1x gtceu:andesite_alloy_drill_head'))
		.notConsumable(Item.of('1x gtceu:raw_coal'))
		.inputFluids(Fluid.of('gtceu:creosote',10))
		.itemOutputs('1x gtceu:raw_coal')
		.duration(100)
		.rpm(32)
})
