ServerEvents.recipes(event => {
	event.remove({ output: 'gtceu:phosphorus_boule' })

	event.recipes.gtceu.electric_blast_furnace('awakened_echo')
		.itemInputs(Item.of('1x gtceu:awakened_echo_dust'))
		.itemOutputs(Item.of('1x gtceu:awakened_echo_ingot'))
		.blastFurnaceTemp(2700)
		.duration(400)
		.EUt(480)	
	event.recipes.gtceu.electric_blast_furnace('natures_alloy')
		.itemInputs(Item.of('1x gtceu:natures_alloy_dust'))
		.itemOutputs(Item.of('1x gtceu:natures_alloy_ingot'))
		.blastFurnaceTemp(900)
		.duration(300)
		.EUt(120)	
	
	event.recipes.gtceu.electric_blast_furnace('purified_iron_ore')
		.itemInputs(Item.of('1x gtceu:crushed_iron_ore'))
		.inputFluids(Fluid.of('kubejs:milky_iron_slurry',144))
		.outputFluids(Fluid.of('gtceu:hydrogen',100))
		.itemOutputs(Item.of('2x gtceu:purified_iron_ore'))
		.blastFurnaceTemp(900)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('andesite_alloy')
		.itemInputs(Item.of('1x create:zinc_nugget'))
		.inputFluids(Fluid.of('kubejs:milky_andesite_alloy_slurry',144))
		.outputFluids(Fluid.of('gtceu:andesite_alloy',288))
		.itemOutputs(Item.of('1x gtceu:asbestos_dust'))
		.blastFurnaceTemp(1900)
		.duration(300)
		.EUt(480)	
	event.recipes.gtceu.electric_blast_furnace('purified_copper_ore')
		.itemInputs(Item.of('1x gtceu:crushed_copper_ore'))
		.inputFluids(Fluid.of('kubejs:carrot_juice',144))
		.outputFluids(Fluid.of('gtceu:nitrogen',100))
		.itemOutputs(Item.of('2x gtceu:purified_copper_ore'))
		.blastFurnaceTemp(900)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('zinc_from_zinc_chloride')
		.inputFluids(Fluid.of('kubejs:zinc_chloride',144))
		.outputFluids(Fluid.of('gtceu:chlorine',72))
		.itemOutputs(Item.of('1x create:zinc_ingot'))
		.blastFurnaceTemp(900)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('blooming_coke')
		.inputFluids(Fluid.of('gtceu:blazing',16))
		.itemInputs(Item.of('1x gtceu:coke_gem'))
		.itemInputs(Item.of('1x minecraft:magma_block'))
		.outputFluids(Fluid.of('gtceu:carbon_dioxide',144))
		.itemOutputs(Item.of('1x kubejs:blooming_coke'))
		.blastFurnaceTemp(1700)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('black_iron')
		.itemInputs(Item.of('1x minecraft:iron_ingot'))
		.inputFluids(Fluid.of('kubejs:infused_source',200))
		.itemOutputs(Item.of('1x extendedcrafting:black_iron_ingot'))
		.blastFurnaceTemp(900)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('silicon_boule')
		.itemInputs(Item.of('32x gtceu:silicon_dust'))
		.itemInputs(Item.of('1x gtceu:arcane_gold_dust'))
		.inputFluids(Fluid.of('kubejs:infused_source',200))
		.itemOutputs(Item.of('1x gtceu:silicon_boule'))
		.blastFurnaceTemp(900)
		.duration(6000)
		.EUt(120)	
		event.recipes.gtceu.electric_blast_furnace('phosphorous_boule')
		.itemInputs(Item.of('64x gtceu:silicon_dust'))
		.itemInputs(Item.of('8x gtceu:awakened_echo_dust'))
		.itemInputs(Item.of('2x gtceu:small_weak_synthetic_dust'))
		.inputFluids(Fluid.of('kubejs:living_matter',8000))
		.itemOutputs(Item.of('1x gtceu:phosphorus_boule'))
		.blastFurnaceTemp(2484)
		.duration(12000)
		.EUt(480)	
	event.recipes.gtceu.electric_blast_furnace('weak_synthetic')
		.itemInputs(Item.of('1x gtceu:weak_synthetic_dust'))
		.itemOutputs(Item.of('1x gtceu:weak_synthetic_ingot'))
		.blastFurnaceTemp(1700)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('magical_alloy')
		.itemInputs(Item.of('1x gtceu:magical_alloy_dust'))
		.itemOutputs(Item.of('1x gtceu:magical_alloy_ingot'))
		.blastFurnaceTemp(1700)
		.duration(600)
		.EUt(120)	
		event.recipes.gtceu.electric_blast_furnace('synthetic_neuron')
		.itemInputs(Item.of('1x gtceu:synthetic_neuron_dust'))
		.itemOutputs(Item.of('1x gtceu:synthetic_neuron_ingot'))
		.blastFurnaceTemp(2700)
		.duration(500)
		.EUt(480)	
	event.recipes.gtceu.electric_blast_furnace('sterile_bio_alloy')
		.itemInputs(Item.of('1x gtceu:sterile_bio_alloy_dust'))
		.itemOutputs(Item.of('1x gtceu:sterile_bio_alloy_ingot'))
		.blastFurnaceTemp(2700)
		.duration(700)
		.EUt(480)	
	event.recipes.gtceu.electric_blast_furnace('virentium_alloy')
		.itemInputs(Item.of('1x gtceu:virentium_alloy_dust'))
		.itemOutputs(Item.of('1x gtceu:hot_virentium_alloy_ingot'))
		.blastFurnaceTemp(3600)
		.duration(800)
		.EUt(640)	
	event.recipes.gtceu.electric_blast_furnace('champions_alloy')
		.itemInputs(Item.of('1x gtceu:champions_alloy_dust'))
		.itemOutputs(Item.of('1x gtceu:hot_champions_alloy_ingot'))
		.blastFurnaceTemp(3600)
		.duration(1000)
		.EUt(1024)	
})
