ServerEvents.recipes(event => {
	event.recipes.gtceu.electric_blast_furnace('awakened_echo')
		.itemInputs(Item.of('1x gtceu:awakened_echo_dust'))
		.itemOutputs(Item.of('1x gtceu:awakened_echo_ingot'))
		.blastFurnaceTemp(2700)
		.duration(400)
		.EUt(480)	
	event.recipes.gtceu.electric_blast_furnace('natures_alloy')
		.itemInputs(Item.of('1x gtceu:natures_alloy_dust'))
		.itemOutputs(Item.of('1x gtceu:natures_alloy_ingot'))
		.blastFurnaceTemp(1000)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('black_iron')
		.itemInputs(Item.of('1x minecraft:iron_ingot'))
		.inputFluids(Fluid.of('kubejs:infused_source',200))
		.itemOutputs(Item.of('1x extended_crafting:black_iron_ingot'))
		.blastFurnaceTemp(1000)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('silicon_boule')
		.itemInputs(Item.of('32x gtceu:silicon_dust'))
		.itemInputs(Item.of('1x gtceu:arcane_gold_dust'))
		.inputFluids(Fluid.of('kubejs:infused_source',200))
		.itemOutputs(Item.of('1x gtceu:silicon_boule'))
		.blastFurnaceTemp(1000)
		.duration(6000)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('weak_synthetic')
		.itemInputs(Item.of('1x gtceu:weak_synthetic_dust'))
		.itemOutputs(Item.of('1x gtceu:weak_synthetic_ingot'))
		.blastFurnaceTemp(1700)
		.duration(300)
		.EUt(120)	
	event.recipes.gtceu.electric_blast_furnace('magical_alloy')
		.itemInputs(Item.of('1x gtceu:magical_alloy_dust'))
		.itemOutputs(Item.of('1x gtceu:magical_alloy_ingot'))
		.blastFurnaceTemp(1700)
		.duration(600)
		.EUt(120)	
})
