ServerEvents.recipes(event => {
	event.recipes.gtceu.caster('casting_iron')
		.inputFluids(Fluid.of('gtceu:iron', 144))
		.itemOutputs('1x minecraft:iron_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_copper')
		.inputFluids(Fluid.of('gtceu:copper', 144))
		.itemOutputs('1x minecraft:copper_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_cupronickel')
		.inputFluids(Fluid.of('gtceu:cupronickel', 144))
		.itemOutputs('1x gtceu:cupronickel_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_brass')
		.inputFluids(Fluid.of('gtceu:brass', 144))
		.itemOutputs('1x gtceu:brass_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_rose_quartz')
		.inputFluids(Fluid.of('kubejs:liquid_rose_quartz', 144))
		.itemOutputs('1x create:rose_quartz')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_andesite_alloy')
		.inputFluids(Fluid.of('gtceu:andesite_alloy', 144))
		.itemOutputs('1x create:andesite_alloy')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_zinc')
		.inputFluids(Fluid.of('gtceu:zinc', 144))
		.itemOutputs('1x gtceu:zinc_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_nickel')
		.inputFluids(Fluid.of('gtceu:nickel', 144))
		.itemOutputs('1x gtceu:nickel_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_rubber')
		.inputFluids(Fluid.of('gtceu:rubber', 144))
		.itemOutputs('1x gtceu:rubber_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_glowing')
		.inputFluids(Fluid.of('gtceu:glowing', 144))
		.itemOutputs('1x gtceu:glowing_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_red_alloy')
		.inputFluids(Fluid.of('gtceu:red_alloy', 144))
		.itemOutputs('1x gtceu:red_alloy_ingot')
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.caster('casting_blazing')
		.inputFluids(Fluid.of('gtceu:blazing', 144))
		.itemOutputs('1x gtceu:blazing_ingot')
		.duration(100)
		.rpm(32)
		event.recipes.gtceu.caster('casting_glass')
		.inputFluids(Fluid.of('gtceu:glass', 144))
		.itemOutputs('1x minecraft:glass')
		.duration(100)
		.rpm(32)
})