ServerEvents.recipes(event => {
	event.recipes.gtceu.centrifuge('mystical_white_1')
		.circuit(0)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:white_mystical_flower')
        .chancedOutput('2x botania:white_mystical_flower',5000,500)
        .chancedOutput('4x botania:white_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_orange_1')
		.circuit(1)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:orange_mystical_flower')
        .chancedOutput('2x botania:orange_mystical_flower',5000,500)
        .chancedOutput('4x botania:orange_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_magenta_1')
		.circuit(2)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:magenta_mystical_flower')
        .chancedOutput('2x botania:magenta_mystical_flower',5000,500)
        .chancedOutput('4x botania:magenta_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_light_blue_1')
		.circuit(3)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:light_blue_mystical_flower')
        .chancedOutput('2x botania:light_blue_mystical_flower',5000,500)
        .chancedOutput('4x botania:light_blue_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_yellow_1')
		.circuit(4)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:yellow_mystical_flower')
        .chancedOutput('2x botania:yellow_mystical_flower',5000,500)
        .chancedOutput('4x botania:yellow_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_lime_1')
		.circuit(5)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:lime_mystical_flower')
        .chancedOutput('2x botania:lime_mystical_flower',5000,500)
        .chancedOutput('4x botania:lime_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_pink_1')
		.circuit(6)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:pink_mystical_flower')
        .chancedOutput('2x botania:pink_mystical_flower',5000,500)
        .chancedOutput('4x botania:pink_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_gray_1')
		.circuit(7)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:gray_mystical_flower')
        .chancedOutput('2x botania:gray_mystical_flower',5000,500)
        .chancedOutput('4x botania:gray_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_light_gray_1')
		.circuit(8)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:light_gray_mystical_flower')
        .chancedOutput('2x botania:light_gray_mystical_flower',5000,500)
        .chancedOutput('4x botania:light_gray_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_cyan_1')
		.circuit(9)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:cyan_mystical_flower')
        .chancedOutput('2x botania:cyan_mystical_flower',5000,500)
        .chancedOutput('4x botania:cyan_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_purple_1')
		.circuit(10)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:purple_mystical_flower')
        .chancedOutput('2x botania:purple_mystical_flower',5000,500)
        .chancedOutput('4x botania:purple_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_blue_1')
		.circuit(11)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:blue_mystical_flower')
        .chancedOutput('2x botania:blue_mystical_flower',5000,500)
        .chancedOutput('4x botania:blue_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_brown_1')
		.circuit(11)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:brown_mystical_flower')
        .chancedOutput('2x botania:brown_mystical_flower',5000,500)
        .chancedOutput('4x botania:brown_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_green_1')
		.circuit(12)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:green_mystical_flower')
        .chancedOutput('2x botania:green_mystical_flower',5000,500)
        .chancedOutput('4x botania:green_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_red_1')
		.circuit(13)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:red_mystical_flower')
        .chancedOutput('2x botania:red_mystical_flower',5000,500)
        .chancedOutput('4x botania:red_petal',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.centrifuge('mystical_black_1')
		.circuit(14)
        .itemInputs(Item.of('4x kubejs:mystical_flowers_1'))
        .itemOutputs('2x botania:black_mystical_flower')
        .chancedOutput('2x botania:black_mystical_flower',5000,500)
        .chancedOutput('4x botania:black_petal',5000,500)
		.duration(40)
		.EUt(7)
})