ServerEvents.recipes(event => {

	event.remove({ output: 'gtceu:plastic_circuit_board'})
	event.remove({ output: 'gtceu:plastic_printed_circuit_board'})

	event.recipes.gtceu.chemical_reactor('infused_source')
		.outputFluids(Fluid.of('kubejs:infused_source', 2000))
		.inputFluids(Fluid.of('kubejs:raw_source', 1000))
		.inputFluids(Fluid.of('gtceu:natures_alloy', 1000))
		.duration(100)
		.EUt(30)
	
	event.recipes.gtceu.chemical_reactor('source_planks')
		.itemInputs(Item.of('8x gtceu:treated_wood_planks'))
		.inputFluids(Fluid.of('kubejs:infused_source', 1000))
		.itemOutputs(Item.of('8x kubejs:source_planks'))
		.duration(60)
		.EUt(16)
	
	event.recipes.gtceu.chemical_reactor('manafloraethylene')
		.itemInputs(Item.of('1x botania:mana_powder'))
		.inputFluids(Fluid.of('kubejs:floraethylene', 1000))
		.outputFluids(Fluid.of('kubejs:manafloraethylene', 1000))
		.duration(60)
		.EUt(120)
	
	event.recipes.gtceu.chemical_reactor('phenolic_circuit_board')
		.itemInputs(Item.of('4x gtceu:elementium_foil'))
		.itemInputs(Item.of('1x botania:livingwood_planks'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 250))
		.itemOutputs(Item.of('2x gtceu:phenolic_circuit_board'))
		.duration(500)
		.EUt(10)
    event.recipes.gtceu.chemical_reactor('phenolic_printed_circuit_board')
		.itemInputs(Item.of('6x gtceu:elementium_foil'))
		.itemInputs(Item.of('1x gtceu:magical_circuit_board'))
		.inputFluids(Fluid.of('kubejs:arcane_infused_growth_medium', 250))
		.itemOutputs(Item.of('1x gtceu:phenolic_printed_circuit_board'))
		.duration(500)
		.EUt(10)
		event.recipes.gtceu.chemical_reactor('plastic_circuit_board')
		.itemInputs(Item.of('1x kubejs:crude_insulator_sheet'))
		.itemInputs(Item.of('4x gtceu:synthetic_neuron_foil'))
		.inputFluids(Fluid.of('kubejs:clean_growth_medium', 250))
		.itemOutputs(Item.of('1x gtceu:plastic_circuit_board'))
		.duration(500)
		.EUt(10)
	event.recipes.gtceu.chemical_reactor('plastic_circuit_board_2')
		.itemInputs(Item.of('1x kubejs:dense_insulator_sheet'))
		.itemInputs(Item.of('4x gtceu:synthetic_neuron_foil'))
		.inputFluids(Fluid.of('kubejs:clean_growth_medium', 250))
		.itemOutputs(Item.of('2x gtceu:plastic_circuit_board'))
		.duration(500)
		.EUt(10)
		event.recipes.gtceu.chemical_reactor('plastic_circuit_board_3')
		.itemInputs(Item.of('1x kubejs:hyper_insulator_sheet'))
		.itemInputs(Item.of('4x gtceu:synthetic_neuron_foil'))
		.inputFluids(Fluid.of('kubejs:clean_growth_medium', 250))
		.itemOutputs(Item.of('4x gtceu:plastic_circuit_board'))
		.duration(500)
		.EUt(10)
    event.recipes.gtceu.chemical_reactor('plastic_printed_circuit_board')
		.itemInputs(Item.of('1x gtceu:plastic_circuit_board'))
		.itemInputs(Item.of('6x gtceu:synthetic_neuron_foil'))
		.inputFluids(Fluid.of('kubejs:living_matter', 250))
		.itemOutputs(Item.of('1x gtceu:plastic_printed_circuit_board'))
		.duration(500)
		.EUt(10)
    event.recipes.gtceu.chemical_reactor('natural_research')
		.itemInputs(Item.of('1x kubejs:raw_meat_glob'))
		.itemInputs(Item.of('1x kubejs:plant_glob'))
		.inputFluids(Fluid.of('gtceu:natures_alloy', 144))
		.inputFluids(Fluid.of('gtceu:sulfuric_acid', 144))
		.inputFluids(Fluid.of('kubejs:crude_insulator', 144))

		.itemOutputs(Item.of('1x kubejs:natural_research'))
		.duration(500)
		.EUt(10)

	  event.recipes.gtceu.chemical_reactor('magical_research')
		.itemInputs(Item.of('1x kubejs:magical_meat_glob'))
		.itemInputs(Item.of('1x kubejs:magical_plant_glob'))
		.inputFluids(Fluid.of('gtceu:magical_alloy', 144))
		.inputFluids(Fluid.of('gtceu:polyvinyl_chloride', 144))
		.inputFluids(Fluid.of('kubejs:crude_insulator', 288))

		.itemOutputs(Item.of('1x kubejs:magical_research'))
		.duration(1000)
		.EUt(32)
})