ServerEvents.recipes(event => {
	event.recipes.gtceu.chemical_reactor('infused_source')
		.outputFluids(Fluid.of('kubejs:infused_source', 1000))
		.inputFluids(Fluid.of('kubejs:raw_source', 1000))
		.inputFluids(Fluid.of('gtceu:natures_alloy', 1000))
		.duration(100)
		.EUt(30)
	
	event.recipes.gtceu.chemical_reactor('source_planks')
		.itemInputs(Item.of('8x gtceu:treated_wood_planks'))
		.inputFluids(Fluid.of('kubejs:infused_source', 1000))
		.itemOutputs(Item.of('8x kubejs:source_planks'))
		.duration(60)
		.EUt(16)
	
	event.recipes.gtceu.chemical_reactor('manafloraethylene')
		.itemInputs(Item.of('1x botania:mana_powder'))
		.inputFluids(Fluid.of('kubejs:floraethylene', 1000))
		.outputFluids(Fluid.of('kubejs:manafloraethylene', 1000))
		.duration(60)
		.EUt(120)
	
	event.recipes.gtceu.chemical_reactor('magical_circuit_board')
		.itemInputs(Item.of('4x gtceu:elementium_foil'))
		.itemInputs(Item.of('1x botania:livingwood_planks'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 250))
		.itemOutputs(Item.of('2x gtceu:magical_circuit_board'))
		.duration(500)
		.EUt(10)
    event.recipes.gtceu.chemical_reactor('magical__printed_circuit_board')
		.itemInputs(Item.of('6x gtceu:elementium_foil'))
		.itemInputs(Item.of('1x gtceu:magical_circuit_board'))
		.inputFluids(Fluid.of('kubejs:arcane_infused_growth_medium', 250))
		.itemOutputs(Item.of('1x gtceu:magical__printed_circuit_board'))
		.duration(500)
		.EUt(10)
})