ServerEvents.recipes(event => {
	event.remove({ output: 'gtceu:basic_integrated_circuit' })
	event.remove({ output: 'gtceu:good_integrated_circuit' })
	event.remove({ output: 'gtceu:advanced_integrated_circuit' })
	event.remove({ output: 'gtceu:microchip_processor' })
	event.remove({ output: 'gtceu:micro_processor' })
	event.remove({ output: 'gtceu:micro_processor_assembly' })
	event.remove({ output: 'gtceu:micro_processor_computer' })
	event.remove({ output: 'gtceu:micro_processor_mainframe' })

	event.recipes.gtceu.circuit_assembler('basic_integrated_circuit')
		.itemInputs(Item.of('1x gtceu:resin_printed_circuit_board'))
		.itemInputs(Item.of('1x gtceu:ilc_chip'))
		.itemInputs(Item.of('2x #gtceu:resistors'))
		.itemInputs(Item.of('2x #gtceu:diodes'))
		.itemInputs(Item.of('2x gtceu:fine_glowing_wire'))
		.itemInputs(Item.of('2x gtceu:natures_alloy_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('2x gtceu:basic_integrated_circuit'))
		.duration(200)
		.EUt(16)
	
	event.recipes.gtceu.circuit_assembler('good_integrated_circuit')
		.itemInputs(Item.of('1x gtceu:phenolic_printed_circuit_board'))
		.itemInputs(Item.of('2x gtceu:basic_integrated_circuit'))
		.itemInputs(Item.of('2x #gtceu:resistors'))
		.itemInputs(Item.of('2x #gtceu:diodes'))
		.itemInputs(Item.of('4x gtceu:fine_weak_synthetic_wire'))
		.itemInputs(Item.of('4x gtceu:natures_alloy_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('2x gtceu:good_integrated_circuit'))
		.duration(400)
		.EUt(24)
	
	event.recipes.gtceu.circuit_assembler('advanced_integrated_circuit')
		.itemInputs(Item.of('1x gtceu:good_integrated_circuit'))
		.itemInputs(Item.of('2x gtceu:ilc_chip'))
		.itemInputs(Item.of('2x gtceu:ram_chip'))
		.itemInputs(Item.of('4x #gtceu:diodes'))
		.itemInputs(Item.of('8x gtceu:fine_weak_synthetic_wire'))
		.itemInputs(Item.of('8x gtceu:awakened_echo_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('1x gtceu:advanced_integrated_circuit'))
		.duration(800)
		.EUt(30)

	event.recipes.gtceu.circuit_assembler('microchip_processor')
		.itemInputs(Item.of('1x gtceu:plastic_printed_circuit_board'))
		.itemInputs(Item.of('1x gtceu:cpu_chip'))
		.itemInputs(Item.of('2x #gtceu:resistors'))
		.itemInputs(Item.of('2x #gtceu:capacitors'))
		.itemInputs(Item.of('2x #gtceu:transistors'))
		.itemInputs(Item.of('2x gtceu:fine_synthetic_neuron_wire'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('3x gtceu:microchip_processor'))
		.duration(200)
		.EUt(60)

		event.recipes.gtceu.circuit_assembler('microchip_processor_2')
		.itemInputs(Item.of('1x gtceu:plastic_printed_circuit_board'))
		.itemInputs(Item.of('1x gtceu:soc'))
		.itemInputs(Item.of('2x gtceu:fine_synthetic_neuron_wire'))
		.itemInputs(Item.of('2x gtceu:sterile_bio_alloy_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('6x gtceu:microchip_processor'))
		.duration(50)
		.EUt(600)
		.cleanroom(CleanroomType.CLEANROOM)

		event.recipes.gtceu.circuit_assembler('micro_processor')
		.itemInputs(Item.of('1x gtceu:plastic_printed_circuit_board'))
		.itemInputs(Item.of('1x gtceu:cpu_chip'))
		.itemInputs(Item.of('4x #gtceu:resistors'))
		.itemInputs(Item.of('4x #gtceu:capacitors'))
		.itemInputs(Item.of('4x #gtceu:transistors'))
		.itemInputs(Item.of('4x gtceu:fine_synthetic_neuron_wire'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',72))
		.itemOutputs(Item.of('2x gtceu:micro_processor'))
		.duration(200)
		.EUt(60)

		event.recipes.gtceu.circuit_assembler('micro_processor_2')
		.itemInputs(Item.of('1x gtceu:plastic_printed_circuit_board'))
		.itemInputs(Item.of('1x gtceu:soc'))
		.itemInputs(Item.of('4x gtceu:fine_synthetic_neuron_wire'))
		.itemInputs(Item.of('4x gtceu:sterile_bio_alloy_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',72))
		.itemOutputs(Item.of('4x gtceu:micro_processor'))
		.duration(50)
		.EUt(2400)
		.cleanroom(CleanroomType.CLEANROOM)

		event.recipes.gtceu.circuit_assembler('micro_processor_assembly')
		.itemInputs(Item.of('1x gtceu:plastic_printed_circuit_board'))
		.itemInputs(Item.of('2x gtceu:micro_processor'))
		.itemInputs(Item.of('4x #gtceu:inductors'))
		.itemInputs(Item.of('8x #gtceu:capacitors'))
		.itemInputs(Item.of('4x gtceu:ram_chip'))
		.itemInputs(Item.of('8x gtceu:fine_synthetic_neuron_wire'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('2x gtceu:micro_processor_assembly'))
		.duration(400)
		.EUt(120)

		event.recipes.gtceu.circuit_assembler('micro_processor_computer')
		.itemInputs(Item.of('1x gtceu:plastic_printed_circuit_board'))
		.itemInputs(Item.of('2x gtceu:micro_processor_assembly'))
		.itemInputs(Item.of('4x #gtceu:diodes'))
		.itemInputs(Item.of('4x gtceu:ram_chip'))
		.itemInputs(Item.of('16x gtceu:fine_synthetic_neuron_wire'))
		.itemInputs(Item.of('16x gtceu:awakened_echo_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('1x gtceu:micro_processor_computer'))
		.duration(400)
		.EUt(120)
		.cleanroom(CleanroomType.CLEANROOM)

		event.recipes.gtceu.circuit_assembler('micro_processor_mainframe')
		.itemInputs(Item.of('2x gtceu:sterile_bio_alloy_frame'))
		.itemInputs(Item.of('2x gtceu:micro_processor_computer'))
		.itemInputs(Item.of('8x #gtceu:inductors'))
		.itemInputs(Item.of('16x #gtceu:capacitors'))
		.itemInputs(Item.of('16x gtceu:ram_chip'))
		.itemInputs(Item.of('16x gtceu:synthetic_neuron_single_wire'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',288))
		.itemOutputs(Item.of('1x gtceu:micro_processor_mainframe'))
		.duration(800)
		.EUt(480)
		.cleanroom(CleanroomType.CLEANROOM)
})
