ServerEvents.recipes(event => {
	event.remove({ output: 'gtceu:basic_integrated_circuit' })
	event.remove({ output: 'gtceu:good_integrated_circuit' })
	event.remove({ output: 'gtceu:advanced_integrated_circuit' })

	event.recipes.gtceu.circuit_assembler('basic_integrated_circuit')
		.itemInputs(Item.of('1x gtceu:resin_printed_circuit_board'))
		.itemInputs(Item.of('1x gtceu:ilc_chip'))
		.itemInputs(Item.of('2x #gtceu:resistors'))
		.itemInputs(Item.of('2x #gtceu:diodes'))
		.itemInputs(Item.of('2x gtceu:fine_glowing_wire'))
		.itemInputs(Item.of('2x gtceu:natures_alloy_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('2x gtceu:basic_integrated_circuit'))
		.duration(200)
		.EUt(16)
	
	event.recipes.gtceu.circuit_assembler('good_integrated_circuit')
		.itemInputs(Item.of('1x gtceu:phenolic_printed_circuit_board'))
		.itemInputs(Item.of('2x gtceu:basic_integrated_circuit'))
		.itemInputs(Item.of('2x #gtceu:resistors'))
		.itemInputs(Item.of('2x #gtceu:diodes'))
		.itemInputs(Item.of('4x gtceu:fine_weak_synthetic_wire'))
		.itemInputs(Item.of('4x gtceu:natures_alloy_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('2x gtceu:good_integrated_circuit'))
		.duration(400)
		.EUt(24)
	
	event.recipes.gtceu.circuit_assembler('advanced_integrated_circuit')
		.itemInputs(Item.of('1x gtceu:good_integrated_circuit'))
		.itemInputs(Item.of('2x gtceu:ilc_chip'))
		.itemInputs(Item.of('2x gtceu:ram_chip'))
		.itemInputs(Item.of('4x #gtceu:diodes'))
		.itemInputs(Item.of('8x gtceu:fine_weak_synthetic_wire'))
		.itemInputs(Item.of('8x gtceu:awakened_echo_bolt'))
		.inputFluids(Fluid.of('kubejs:crude_insulator',144))
		.itemOutputs(Item.of('1x gtceu:advanced_integrated_circuit'))
		.duration(800)
		.EUt(30)
})
