ServerEvents.recipes(event => {
	event.recipes.gtceu.crop_simulator('wheat_seeds_0')
		.notConsumable(Item.of('1x minecraft:wheat_seeds'))
		.inputFluids(Fluid.of('minecraft:water', 100))
		.itemOutputs(Item.of('1x minecraft:wheat'))
		.chancedOutput('1x minecraft:wheat_seeds', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('wheat_seeds_1')
		.itemInputs(Item.of('1x kubejs:wheat_seeds_mk1'))
		.inputFluids(Fluid.of('minecraft:water', 100))
		.itemOutputs(Item.of('8x minecraft:wheat'))
		.chancedOutput('1x kubejs:wheat_seeds_mk1', 9000, 0)
		.chancedOutput('1x kubejs:wheat_seeds_mk1', 500, 500)
		.duration(12000)
		.EUt(32)	

	event.recipes.gtceu.crop_simulator('poppy_0')
		.notConsumable(Item.of('1x minecraft:poppy'))
		.inputFluids(Fluid.of('minecraft:water', 100))
		.itemOutputs(Item.of('1x minecraft:poppy'))
		.chancedOutput('1x minecraft:poppy', 5000, 500)
		.duration(12000)
		.EUt(8)	
})
