ServerEvents.recipes(event => {
	event.recipes.gtceu.distillery('living_matter')
		.circuit(1)
		.inputFluids(Fluid.of('kubejs:sterile_meat', 1000))
        .outputFluids(Fluid.of('kubejs:living_matter', 500))
		.itemOutputs(Item.of('1x gtceu:sterile_bio_alloy_dust'))
		.duration(2000)
		.EUt(120)

	event.recipes.gtceu.distillery('living_matter_2')
		.circuit(2)
		.inputFluids(Fluid.of('kubejs:sterile_meat', 1000))
        .outputFluids(Fluid.of('kubejs:dense_insulator', 500))
		.itemOutputs(Item.of('1x gtceu:sterile_bio_alloy_dust'))
		.duration(2000)
		.EUt(120)
})