ServerEvents.recipes(event => {
	event.recipes.gtceu.extractor('raw_source')
		.itemInputs(Item.of('16x ars_nouveau:sourceberry_bush'))
		.outputFluids(Fluid.of('kubejs:raw_source', 1000))
		.duration(200)
		.EUt(30)

	event.recipes.gtceu.extractor('honey')
		.itemInputs(Item.of('1x minecraft:honey_block'))
		.outputFluids(Fluid.of('create:honey', 1000))
		.duration(200)
		.EUt(2)
	
	event.recipes.gtceu.extractor('honeycomb')
		.itemInputs(Item.of('1x minecraft:honeycomb'))
		.outputFluids(Fluid.of('create:honey', 100))
		.duration(40)
		.EUt(2)
	
	event.recipes.gtceu.extractor('white_petal')
		.itemInputs(Item.of('16x botania:white_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('black_petal')
		.itemInputs(Item.of('16x botania:black_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('brown_petal')
		.itemInputs(Item.of('16x botania:brown_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('gray_petal')
		.itemInputs(Item.of('16x botania:gray_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('light_gray_petal')
		.itemInputs(Item.of('16x botania:light_gray_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('red_petal')
		.itemInputs(Item.of('16x botania:red_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('orange_petal')
		.itemInputs(Item.of('16x botania:orange_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('yellow_petal')
		.itemInputs(Item.of('16x botania:yellow_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('green_petal')
		.itemInputs(Item.of('16x botania:green_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('blue_petal')
		.itemInputs(Item.of('16x botania:blue_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('purple_petal')
		.itemInputs(Item.of('16x botania:purple_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('pink_petal')
		.itemInputs(Item.of('16x botania:pink_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('lime_petal')
		.itemInputs(Item.of('16x botania:lime_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('light_blue_petal')
		.itemInputs(Item.of('16x botania:light_blue_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('cyan_petal')
		.itemInputs(Item.of('16x botania:cyan_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
	event.recipes.gtceu.extractor('magenta_petal')
		.itemInputs(Item.of('16x botania:magenta_petal'))
		.outputFluids(Fluid.of('kubejs:floroethylene', 1000))
		.duration(200)
		.EUt(30)
})