ServerEvents.recipes(event => {

	event.recipes.gtceu.fluid_solidifier('crude_insulator_sheet')
        .notConsumable(Item.of('1x kubejs:plate_casting_mold'))
		.inputFluids(Fluid.of('kubejs:crude_insulator', 144))
        .itemOutputs('1x kubejs:crude_insulator_sheet')
		.duration(40)
		.EUt(7)
        event.recipes.gtceu.fluid_solidifier('dende_insulator_sheet')
        .notConsumable(Item.of('1x kubejs:plate_casting_mold'))
		.inputFluids(Fluid.of('kubejs:dense_insulator', 144))
        .itemOutputs('1x kubejs:dense_insulator_sheet')
		.duration(40)
		.EUt(7)
        event.recipes.gtceu.fluid_solidifier('hyper_insulator_sheet')
        .notConsumable(Item.of('1x kubejs:plate_casting_mold'))
		.inputFluids(Fluid.of('kubejs:hyper_insulator', 144))
        .itemOutputs('1x kubejs:hyper_insulator_sheet')
		.duration(40)
		.EUt(7)
	
        event.recipes.gtceu.fluid_solidifier('nether_shard')
        .itemInputs('1x kubejs:blank_shard')
		.inputFluids(Fluid.of('kubejs:nether_essence', 1000))
        .itemOutputs('1x kubejs:nether_shard')
		.duration(40)
		.EUt(7)
	
        event.recipes.gtceu.fluid_solidifier('earth_shard')
        .itemInputs('1x kubejs:blank_shard')
		.inputFluids(Fluid.of('kubejs:earth_essence', 1000))
        .itemOutputs('1x kubejs:earth_shard')
		.duration(40)
		.EUt(7)
	
        event.recipes.gtceu.fluid_solidifier('desert_shard')
        .itemInputs('1x kubejs:blank_shard')
		.inputFluids(Fluid.of('kubejs:desert_essence', 1000))
        .itemOutputs('1x kubejs:desert_shard')
		.duration(40)
		.EUt(7)

        event.recipes.gtceu.fluid_solidifier('jungle_shard')
        .itemInputs('1x kubejs:blank_shard')
		.inputFluids(Fluid.of('kubejs:jungle_essence', 1000))
        .itemOutputs('1x kubejs:jungle_shard')
		.duration(40)
		.EUt(7)

        event.recipes.gtceu.fluid_solidifier('sky_shard')
        .itemInputs('1x kubejs:blank_shard')
		.inputFluids(Fluid.of('kubejs:sky_essence', 1000))
        .itemOutputs('1x kubejs:sky_shard')
		.duration(40)
		.EUt(7)
	
        event.recipes.gtceu.fluid_solidifier('ocean_shard')
        .itemInputs('1x kubejs:blank_shard')
		.inputFluids(Fluid.of('kubejs:ocean_essence', 1000))
        .itemOutputs('1x kubejs:ocean_shard')
		.duration(40)
		.EUt(7)
	
        event.recipes.gtceu.fluid_solidifier('ender_shard')
        .itemInputs('1x kubejs:blank_shard')
		.inputFluids(Fluid.of('kubejs:ender_essence', 1000))
        .itemOutputs('1x kubejs:ender_shard')
		.duration(40)
		.EUt(7)

        event.recipes.gtceu.fluid_solidifier('taiga_shard')
        .itemInputs('1x kubejs:blank_shard')
		.inputFluids(Fluid.of('kubejs:taiga_essence', 1000))
        .itemOutputs('1x kubejs:taiga_shard')
		.duration(40)
		.EUt(7)
})