ServerEvents.recipes(event => {

	event.recipes.gtceu.fluid_solidifier('crude_insulator_sheet')
        .notConsumable(Item.of('1x kubejs:plate_casting_mold'))
		.inputFluids(Fluid.of('kubejs:crude_insulator', 144))
        .itemOutputs('1x kubejs:crude_insulator_sheet')
		.duration(40)
		.EUt(7)
        event.recipes.gtceu.fluid_solidifier('dende_insulator_sheet')
        .notConsumable(Item.of('1x kubejs:plate_casting_mold'))
		.inputFluids(Fluid.of('kubejs:dense_insulator', 144))
        .itemOutputs('1x kubejs:dense_insulator_sheet')
		.duration(40)
		.EUt(7)
        event.recipes.gtceu.fluid_solidifier('hyper_insulator_sheet')
        .notConsumable(Item.of('1x kubejs:plate_casting_mold'))
		.inputFluids(Fluid.of('kubejs:hyper_insulator', 144))
        .itemOutputs('1x kubejs:hyper_insulator_sheet')
		.duration(40)
		.EUt(7)
})