ServerEvents.recipes(event => {
	event.recipes.gtceu.foundry('melting_iron')
		.itemInputs('1x #forge:ingots/iron')
		.outputFluids(Fluid.of('gtceu:iron', 144))
		.inputFluids(Fluid.of('minecraft:lava', 10))
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.foundry('melting_andesite')
		.itemInputs('1x create:andesite_alloy')
		.outputFluids(Fluid.of('gtceu:andesite_alloy', 144))
		.inputFluids(Fluid.of('minecraft:lava', 10))
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.foundry('melting_copper')
		.itemInputs('1x #forge:ingots/copper')
		.outputFluids(Fluid.of('gtceu:copper', 144))
		.inputFluids(Fluid.of('minecraft:lava', 10))
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.foundry('melting_zinc')
		.itemInputs('1x #forge:ingots/zinc')
		.outputFluids(Fluid.of('gtceu:zinc', 144))
		.inputFluids(Fluid.of('minecraft:lava', 10))
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.foundry('melting_nickel')
		.itemInputs('1x #forge:ingots/nickel')
		.outputFluids(Fluid.of('gtceu:nickel', 144))
		.inputFluids(Fluid.of('minecraft:lava', 10))
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.foundry('melting_redstone')
		.itemInputs('1x minecraft:redstone')
		.outputFluids(Fluid.of('gtceu:redstone', 144))
		.inputFluids(Fluid.of('minecraft:lava', 10))
		.duration(100)
		.rpm(32)
	event.recipes.gtceu.foundry('melting_rubber')
		.itemInputs('1x gtceu:sticky_resin')
		.outputFluids(Fluid.of('gtceu:rubber', 144))
		.inputFluids(Fluid.of('minecraft:lava', 10))
		.duration(100)
		.rpm(32)
})