ServerEvents.recipes(event => {
	event.recipes.gtceu.laboratory('primitive_research')
		.itemInputs(Item.of('8x kubejs:sparkling_andesite_dust'))
		.itemInputs(Item.of('4x allthecompressed:dirt_1x'))
		.itemInputs(Item.of('4x kubejs:dense_insulator_sheet'))
		.itemInputs(Item.of('2x farmersdelight:vegetable_soup'))
		.itemInputs(Item.of('1x gtceu:purified_iron_ore'))
		.inputFluids(Fluid.of('gtceu:carbon_monoxide', 1000))
		.itemOutputs(Item.of('16x kubejs:primitive_research'))
		.duration(200)
		.EUt(480)	
	
	event.recipes.gtceu.laboratory('andesite_research')
		.itemInputs(Item.of('8x gtceu:coke_oven_bricks'))
		.itemInputs(Item.of('4x allthecompressed:andesite_2x'))
		.itemInputs(Item.of('4x kubejs:blooming_coke'))
		.itemInputs(Item.of('2x gtceu:andesite_alloy_ring'))
		.itemInputs(Item.of('1x kubejs:mega_andesite_casing'))
		.inputFluids(Fluid.of('kubejs:zinc_chloride', 1000))
		.itemOutputs(Item.of('16x kubejs:andesite_research'))
		.duration(200)
		.EUt(480)
})
