ServerEvents.recipes(event => {
	event.recipes.gtceu.large_mechanical_press('mega_andesite_casing')
		.itemInputs('16x create:andesite_casing')
		.itemInputs('2x create:electron_tube')
		.itemInputs('create:precision_mechanism')
		.inputFluids(Fluid.of('kubejs:ender_essence', 144))
		.itemOutputs('kubejs:mega_andesite_casing')

		.duration(200)
		.rpm(128)
	event.recipes.gtceu.large_mechanical_press('mega_brass_casing')
		.itemInputs('16x create:brass_casing')
		.itemInputs('2x create:electron_tube')
		.itemInputs('create:precision_mechanism')
		.inputFluids(Fluid.of('kubejs:ender_essence', 144))
		.itemOutputs('kubejs:mega_brass_casing')

	event.recipes.gtceu.large_mechanical_press('mega_copper_casing')
		.itemInputs('16x create:copper_casing')
		.itemInputs('2x create:electron_tube')
		.itemInputs('create:precision_mechanism')
		.inputFluids(Fluid.of('kubejs:ender_essence', 144))
		.itemOutputs('kubejs:mega_copper_casing')

		.duration(200)
		.rpm(128)
	event.recipes.gtceu.large_mechanical_press('brass_casing')
		.itemInputs('1x gtceu:brass_plate')
		.itemInputs('1x gtceu:treated_wood_planks')
		.itemOutputs('create:brass_casing')
		.duration(20)
		.rpm(64)
	event.recipes.gtceu.large_mechanical_press('andesite_casing')
		.itemInputs('1x gtceu:andesite_alloy_plate')
		.itemInputs('1x gtceu:treated_wood_planks')
		.itemOutputs('create:andesite_casing')
		.duration(20)
		.rpm(64)
	event.recipes.gtceu.large_mechanical_press('copper_casing')
		.itemInputs('1x gtceu:cupronickel_plate')
		.itemInputs('1x gtceu:treated_wood_planks')
		.itemOutputs('create:copper_casing')
		.duration(20)
		.rpm(64)
	event.recipes.gtceu.large_mechanical_press('blaze_cake')
		.itemInputs('1x create:blaze_cake_base')
		.itemInputs('4x gtceu:sulfur_dust')
		.inputFluids(Fluid.of('minecraft:lava', 250))
		.itemOutputs('create:blaze_cake')

})