ServerEvents.recipes(event => {
    event.remove({ output: 'minecraft:wheat', type: 'gtceu:macerator' })

	event.recipes.gtceu.macerator('wheat_0')
        .itemInputs(Item.of('4x minecraft:wheat'))
        .itemOutputs('2x minecraft:wheat')
        .itemOutputs('2x minecraft:wheat_seeds')
        .chancedOutput('2x minecraft:wheat',5000,500)
        .chancedOutput('2x minecraft:wheat_seeds',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.macerator('wheat_1')
        .itemInputs(Item.of('4x kubejs:wheat_1'))
        .itemOutputs('2x kubejs:wheat_1')
        .itemOutputs('2x kubejs:wheat_seeds_1')
        .chancedOutput('2x minecraft:wheat',5000,500)
        .chancedOutput('2x minecraft:wheat_seeds',5000,500)
		.duration(40)
		.EUt(7)

        event.recipes.gtceu.macerator('wheat_2')
        .itemInputs(Item.of('4x kubejs:wheat_2'))
        .itemOutputs('2x kubejs:wheat_2')
        .itemOutputs('2x kubejs:wheat_seeds_2')
        .chancedOutput('2x kubejs:wheat_1',5000,500)
        .chancedOutput('2x kubejs:wheat_seeds_1',5000,500)
		.duration(40)
		.EUt(7)
	
	

	event.recipes.gtceu.macerator('pumpkin_1')
        .itemInputs(Item.of('4x kubejs:pumpkin_1'))
        .itemOutputs('2x kubejs:pumpkin_1')
        .itemOutputs('2x kubejs:pumpkin_seeds_1')
        .chancedOutput('2x minecraft:pumpkin',5000,500)
        .chancedOutput('2x minecraft:pumpkin_seeds',5000,500)
		.duration(40)
		.EUt(7)

        event.recipes.gtceu.macerator('pumpkin_2')
        .itemInputs(Item.of('4x kubejs:pumpkin_2'))
        .itemOutputs('2x kubejs:pumpkin_2')
        .itemOutputs('2x kubejs:pumpkin_seeds_2')
        .chancedOutput('2x kubejs:pumpkin_1',5000,500)
        .chancedOutput('2x kubejs:pumpkin_seeds_1',5000,500)
		.duration(40)
		.EUt(7)

//carrots
	event.recipes.gtceu.macerator('carrots_1')
        .itemInputs(Item.of('4x kubejs:carrots_1'))
        .itemOutputs('16x minecraft:carrot')
        .chancedOutput('8x minecraft:carrot',1000,1000)
		.duration(40)
		.EUt(7)
	
//essence
		event.recipes.gtceu.macerator('nether_dust')
        .itemInputs(Item.of('1x kubejs:nether_shard'))
        .itemOutputs('2x kubejs:nether_dust')
		.duration(40)
		.EUt(7)
			event.recipes.gtceu.macerator('earth_dust')
        .itemInputs(Item.of('1x kubejs:earth_shard'))
        .itemOutputs('2x kubejs:earth_dust')
		.duration(40)
		.EUt(7)
			event.recipes.gtceu.macerator('desert_dust')
        .itemInputs(Item.of('1x kubejs:desert_shard'))
        .itemOutputs('2x kubejs:desert_dust')
		.duration(40)
		.EUt(7)
			event.recipes.gtceu.macerator('jungle_dust')
        .itemInputs(Item.of('1x kubejs:jungle_shard'))
        .itemOutputs('2x kubejs:jungle_dust')
		.duration(40)
		.EUt(7)
			event.recipes.gtceu.macerator('sky_dust')
        .itemInputs(Item.of('1x kubejs:sky_shard'))
        .itemOutputs('2x kubejs:sky_dust')
		.duration(40)
		.EUt(7)
			event.recipes.gtceu.macerator('ocean_dust')
        .itemInputs(Item.of('1x kubejs:ocean_shard'))
        .itemOutputs('2x kubejs:ocean_dust')
		.duration(40)
		.EUt(7)
			event.recipes.gtceu.macerator('ender_dust')
        .itemInputs(Item.of('1x kubejs:ender_shard'))
        .itemOutputs('2x kubejs:ender_dust')
		.duration(40)
		.EUt(7)
			event.recipes.gtceu.macerator('taiga_dust')
        .itemInputs(Item.of('1x kubejs:taiga_shard'))
        .itemOutputs('2x kubejs:taiga_dust')
		.duration(40)
		.EUt(7)
})