ServerEvents.recipes(event => {
    event.remove({ output: 'minecraft:wheat', type: 'gtceu:macerator' })

	event.recipes.gtceu.macerator('wheat_0')
        .itemInputs(Item.of('4x minecraft:wheat'))
        .itemOutputs('2x minecraft:wheat')
        .itemOutputs('2x minecraft:wheat_seeds')
        .chancedOutput('2x minecraft:wheat',5000,500)
        .chancedOutput('2x minecraft:wheat_seeds',5000,500)
		.duration(40)
		.EUt(7)
	event.recipes.gtceu.macerator('wheat_1')
        .itemInputs(Item.of('4x kubejs:wheat_1'))
        .itemOutputs('2x kubejs:wheat_1')
        .itemOutputs('2x kubejs:wheat_seeds_1')
        .chancedOutput('2x minecraft:wheat',5000,500)
        .chancedOutput('2x minecraft:wheat_seeds',5000,500)
		.duration(40)
		.EUt(7)

        event.recipes.gtceu.macerator('wheat_2')
        .itemInputs(Item.of('4x kubejs:wheat_2'))
        .itemOutputs('2x kubejs:wheat_2')
        .itemOutputs('2x kubejs:wheat_seeds_2')
        .chancedOutput('2x kubejs:wheat_1',5000,500)
        .chancedOutput('2x kubejs:wheat_seeds_1',5000,500)
		.duration(40)
		.EUt(7)
})