ServerEvents.recipes(event => {
	event.recipes.gtceu.meat_freezer('clean_growth_medium')
		.inputFluids(Fluid.of('kubejs:arcane_infused_growth_medium',1000))
		.inputFluids(Fluid.of('kubejs:manafloraethylene',1000))

		.itemInputs(Item.of('1x botania:corporea_spark_master'))
		.outputFluids(Fluid.of('kubejs:clean_growth_medium',2000))

		.duration(200)
		.EUt(120)	

	event.recipes.gtceu.meat_freezer('sterile_meat')
		.itemInputs(Item.of('1x minecraft:beef'))
		.itemInputs(Item.of('1x minecraft:mutton'))
		.itemInputs(Item.of('1x minecraft:chicken'))
		.itemInputs(Item.of('1x minecraft:salmon'))
		.itemInputs(Item.of('1x minecraft:rabbit'))
		.itemInputs(Item.of('1x minecraft:porkchop'))
		.inputFluids(Fluid.of('kubejs:clean_growth_medium',288))
		.inputFluids(Fluid.of('gtceu:fermented_biomass',288))
		.itemOutputs(Item.of('1x kubejs:sterile_meat'))
		.duration(200)
		.EUt(480)	
	
	event.recipes.gtceu.meat_freezer('sterile_meat_glob')
		.itemInputs(Item.of('16x kubejs:magical_meat_glob'))
		.itemInputs(Item.of('8x kubejs:sterile_meat'))
		.itemInputs(Item.of('4x gtceu:fine_synthetic_neuron_wire'))
		.itemInputs(Item.of('4x gtceu:sodium_bisulfate_dust'))
		.itemInputs(Item.of('2x farmersdelight:bacon_and_eggs'))
		.itemInputs(Item.of('2x farmersdelight:steak_and_potatoes'))
		.inputFluids(Fluid.of('kubejs:clean_growth_medium',288))
		.inputFluids(Fluid.of('gtceu:fermented_biomass',288))
		.itemOutputs(Item.of('1x kubejs:sterile_meat_glob'))
		.duration(200)
		.EUt(480)	
	
	event.recipes.gtceu.meat_freezer('sterile_plant_glob')
		.itemInputs(Item.of('16x kubejs:magical_plant_glob'))
		.itemInputs(Item.of('4x deeperdarker:echo_sapling'))
		.itemInputs(Item.of('4x gtceu:fine_weak_synthetic_wire'))
		.itemInputs(Item.of('4x gtceu:clay_dust'))
		.itemInputs(Item.of('2x farmersdelight:mushroom_rice'))
		.itemInputs(Item.of('2x farmersdelight:vegetable_noodles'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene',288))
		.inputFluids(Fluid.of('kubejs:living_matter',288))
		.itemOutputs(Item.of('1x kubejs:sterile_plant_glob'))
		.duration(200)
		.EUt(480)	
	
	event.recipes.gtceu.meat_freezer('lab_fluid')
		.itemInputs(Item.of('1x kubejs:raw_meat_glob'))
		.itemInputs(Item.of('1x minecraft:phantom_membrane'))
		.itemInputs(Item.of('1x minecraft:rotten_flesh'))
		.itemInputs(Item.of('1x gtceu:carbon_dust'))
		.itemInputs(Item.of('1x gtceu:synthetic_neuron_foil'))
		.itemInputs(Item.of('1x kubejs:crude_insulator_sheet'))
		.inputFluids(Fluid.of('kubejs:floraethylene',144))
		.inputFluids(Fluid.of('kubejs:infused_source',144))
		.outputFluids(Fluid.of('kubejs:life_activated_bioplastic',1152))
		.duration(200)
		.EUt(480)	

	event.recipes.gtceu.meat_freezer('flawless_amethyst')
		.itemInputs(Item.of('1x gtceu:purified_amethyst_ore'))
		.inputFluids(Fluid.of('kubejs:glass_residue',288))
		.itemOutputs(Item.of('1x gtceu:flawless_amethyst_gem'))
		.duration(200)
		.EUt(480)	
})
