ServerEvents.recipes(event => {
	event.recipes.gtceu.mega_press('mega_lv_casing')
		.itemInputs(Item.of('8x gtceu:lv_machine_casing'))
		.itemInputs(Item.of('2x gtceu:cupronickel_coil_block'))
		.itemInputs(Item.of('4x #gtceu:circuits/mv'))
		.itemInputs(Item.of('2x gtceu:lv_robot_arm'))
		.itemInputs(Item.of('2x gtceu:lv_electric_pump'))
		.itemInputs(Item.of('2x gtceu:lv_emitter'))
		.inputFluids(Fluid.of('gtceu:polyethylene',144))
		.inputFluids(Fluid.of('gtceu:carbon_dioxide',144))
		.itemOutputs(Item.of('1x kubejs:mega_lv_machine_casing'))
		.duration(900)
		.EUt(120)	

	event.recipes.gtceu.mega_press('mega_mv_casing')
		.itemInputs(Item.of('8x gtceu:mv_machine_casing'))
		.itemInputs(Item.of('2x gtceu:kanthal_coil_block'))
		.itemInputs(Item.of('4x #gtceu:circuits/hv'))
		.itemInputs(Item.of('2x gtceu:mv_robot_arm'))
		.itemInputs(Item.of('2x gtceu:mv_electric_pump'))
		.itemInputs(Item.of('2x gtceu:mv_emitter'))
		.inputFluids(Fluid.of('gtceu:polyvinyl_chloride',144))
		.inputFluids(Fluid.of('kubejs:manafloraethylene',144))
		.itemOutputs(Item.of('1x kubejs:mega_mv_machine_casing'))
		.duration(1200)
		.EUt(480)	
})
