ServerEvents.recipes(event => {
	event.recipes.gtceu.mixer('arcane_gold_dust')
		.itemInputs(Item.of('1x kubejs:source_gem_dust'))
		.itemInputs(Item.of('1x gtceu:gold_dust'))
		.itemOutputs(Item.of('2x gtceu:arcane_gold_dust'))
		.duration(200)
		.EUt(8)	
	event.recipes.gtceu.mixer('growth_medium')
		.itemInputs(Item.of('16x #forge:mushrooms'))
		.itemInputs(Item.of('16x minecraft:moss_block'))
		.itemInputs(Item.of('1x botania:spark'))
		.inputFluids(Fluid.of('minecraft:water',1000))
		.outputFluids(Fluid.of('kubejs:growth_medium',1000))
		.duration(200)
		.EUt(16)
	event.recipes.gtceu.mixer('natures_alloy_dust')
		.itemInputs(Item.of('1x kubejs:ender_dust'))
		.itemInputs(Item.of('1x kubejs:taiga_dust'))
		.itemInputs(Item.of('1x kubejs:jungle_dust'))
		.itemInputs(Item.of('1x kubejs:sky_dust'))
		.itemInputs(Item.of('1x kubejs:ocean_dust'))
		.itemInputs(Item.of('1x kubejs:nether_dust'))
		.itemInputs(Item.of('1x kubejs:earth_dust'))
		.itemInputs(Item.of('1x kubejs:desert_dust'))
		.itemOutputs(Item.of('8x gtceu:natures_alloy_dust'))
		.duration(200)
		.EUt(16)	
	event.recipes.gtceu.mixer('raw_meat_glob')
		.itemInputs(Item.of('1x minecraft:chicken'))
		.itemInputs(Item.of('1x minecraft:beef'))
		.itemInputs(Item.of('1x minecraft:porkchop'))
		.itemInputs(Item.of('1x minecraft:mutton'))
		.itemInputs(Item.of('1x minecraft:rabbit'))
		.itemInputs(Item.of('1x #forge:raw_fishes'))
		.inputFluids(Fluid.of('kubejs:fermented_garlic_honey',144))
		.inputFluids(Fluid.of('gtceu:blazing',144))
		.itemOutputs(Item.of('6x kubejs:raw_meat_glob'))
		.duration(200)
		.EUt(16)
	event.recipes.gtceu.mixer('plant_glob')
		.itemInputs(Item.of('1x #forge:seeds'))
		.itemInputs(Item.of('1x #minecraft:saplings'))
		.itemInputs(Item.of('1x #minecraft:leaves'))
		.itemInputs(Item.of('1x minecraft:moss_block'))
		.itemInputs(Item.of('1x #forge:vegetables'))
		.itemInputs(Item.of('1x minecraft:sweet_berries'))
		.inputFluids(Fluid.of('kubejs:melon_juice',144))
		.inputFluids(Fluid.of('kubejs:dandelion_juice',144))
		.itemOutputs(Item.of('6x kubejs:plant_glob'))
		.duration(200)
		.EUt(16)
	event.recipes.gtceu.mixer('andesite_research_2')
		.itemInputs(Item.of('4x allthecompressed:andesite_1x'))
		.itemInputs(Item.of('1x create:gearbox'))
		.itemInputs(Item.of('16x gtceu:coke_oven_brick'))
		.itemInputs(Item.of('4x gtceu:coke_gem'))
		.itemInputs(Item.of('4x gtceu:andesite_alloy_screw'))
		.itemInputs(Item.of('4x create:crushed_raw_zinc'))
		.inputFluids(Fluid.of('gtceu:creosote',288))
		.inputFluids(Fluid.of('kubejs:glass_residue',144))
		.itemOutputs(Item.of('4x kubejs:andesite_research'))
		.duration(200)
		.EUt(16)
	event.recipes.gtceu.mixer('vegetable_soup')
		.itemInputs(Item.of('64x minecraft:carrot'))
		.itemInputs(Item.of('64x minecraft:potato'))
		.itemInputs(Item.of('64x veggiesdelight:bellpepper'))
		.itemInputs(Item.of('64x veggiesdelight:garlic_clove'))
		.itemInputs(Item.of('64x veggiesdelight:turnip'))
		.itemInputs(Item.of('64x veggiesdelight:zucchini'))
		.inputFluids(Fluid.of('kubejs:dandelion_juice',288))
		.inputFluids(Fluid.of('kubejs:carrot_juice',288))
		.itemOutputs(Item.of('8x farmersdelight:vegetable_soup'))
		.duration(2000)
		.EUt(16)	
	event.recipes.gtceu.mixer('fruit_salad')
		.itemInputs(Item.of('64x create:honeyed_apple'))
		.itemInputs(Item.of('64x minecraft:melon_slice'))
		.itemInputs(Item.of('64x minecraft:glow_berries'))
		.itemInputs(Item.of('64x farmersdelight:pumpkin_slice'))
		.itemInputs(Item.of('64x minecraft:sweet_berries'))
		.itemInputs(Item.of('64x minecraft:sugar'))
		.inputFluids(Fluid.of('kubejs:carrot_juice',288))
		.inputFluids(Fluid.of('kubejs:melon_juice',288))
		.itemOutputs(Item.of('8x farmersdelight:fruit_salad'))
		.duration(2000)
		.EUt(16)	

})
