ServerEvents.recipes(event => {
	event.recipes.gtceu.twilight_awakening_chamber_mk1('naga_trophy')
		.notConsumable(Item.of('1x kubejs:hostile_sample_1'))
		.itemInputs(Item.of('1x #gtceu:circuits/ev'))
		.itemInputs(Item.of('1x kubejs:unborn_naga_trophy'))
		.itemInputs(Item.of('4x twilightforest:naga_scale'))
		.inputFluids(Fluid.of('kubejs:arcane_infused_growth_medium', 1000))
		.itemOutputs(Item.of('1x twilightforest:naga_trophy'))
		.duration(600)
		.EUt(480)	
	event.recipes.gtceu.twilight_awakening_chamber_mk1('lich_trophy')
		.notConsumable(Item.of('1x kubejs:hostile_sample_1'))
		.itemInputs(Item.of('1x #gtceu:circuits/ev'))
		.itemInputs(Item.of('1x kubejs:unborn_lich_trophy'))
		.itemInputs(Item.of('16x minecraft:gold_block'))
		.inputFluids(Fluid.of('kubejs:clean_growth_medium', 1000))
		.itemOutputs(Item.of('1x twilightforest:lich_trophy'))
		.duration(600)
		.EUt(480)	
	event.recipes.gtceu.twilight_awakening_chamber_mk2('hydra_trophy')
		.notConsumable(Item.of('1x kubejs:hostile_sample_2'))
		.itemInputs(Item.of('1x kubejs:unborn_hydra_trophy'))
		.itemInputs(Item.of('1x #gtceu:circuits/ev'))
		.itemInputs(Item.of('16x twilightforest:fiery_blood'))
		.inputFluids(Fluid.of('kubejs:clean_growth_medium', 1000))
		.itemOutputs(Item.of('1x twilightforest:hydra_trophy'))
		.duration(600)
		.EUt(1024)	
	event.recipes.gtceu.twilight_awakening_chamber_mk3('urghast_trophy')
		.notConsumable(Item.of('1x kubejs:hostile_sample_2'))
		.itemInputs(Item.of('1x #gtceu:circuits/ev'))
		.itemInputs(Item.of('1x kubejs:unborn_urghast_trophy'))
		.itemInputs(Item.of('16x twilightforest:carminite'))
		.inputFluids(Fluid.of('kubejs:twilight_infused_growth_medium', 1000))
		.itemOutputs(Item.of('1x twilightforest:ur_ghast_trophy'))
		.duration(600)
		.EUt(1024)	
	event.recipes.gtceu.twilight_awakening_chamber_mk4('snow_queen_trophy')
		.notConsumable(Item.of('1x kubejs:hostile_sample_2'))
		.itemInputs(Item.of('1x #gtceu:circuits/ev'))
		.itemInputs(Item.of('1x kubejs:unborn_snow_queen_trophy'))
		.itemInputs(Item.of('16x minecraft:blue_ice'))
		.inputFluids(Fluid.of('kubejs:twilight_infused_growth_medium', 1000))
		.itemOutputs(Item.of('1x twilightforest:snow_queen_trophy'))
		.duration(600)
		.EUt(2048)	
	
	
//
	event.recipes.gtceu.twilight_awakening_chamber_mk1('virentium')
		.notConsumable(Item.of('1x kubejs:hostile_sample_1'))
		.itemInputs(Item.of('4x kubejs:netherite_scrap_dust'))
		.itemInputs(Item.of('4x kubejs:gaianite_dust'))
		.itemInputs(Item.of('1x twilightforest:naga_scale'))
		.itemOutputs(Item.of('1x gtceu:virentium_alloy_dust'))
		.duration(1200)
		.EUt(480)	
	
	event.recipes.gtceu.twilight_awakening_chamber_mk1('dimlite')
		.notConsumable(Item.of('1x kubejs:hostile_sample_1'))
		.itemInputs(Item.of('4x minecraft:echo_shard'))
		.itemInputs(Item.of('4x terramity:untapped_dimlite'))
		.itemInputs(Item.of('1x twilightforest:ironwood'))
		.itemOutputs(Item.of('1x terramity:dimlite_ingot'))
		.duration(1200)
		.EUt(480)

	event.recipes.gtceu.twilight_awakening_chamber_mk1('cosmilite')
		.notConsumable(Item.of('1x kubejs:hostile_sample_1'))
		.itemInputs(Item.of('4x minecraft:gold_ingot'))
		.itemInputs(Item.of('4x terramity:raw_cosmilite'))
		.itemInputs(Item.of('1x minecraft:enderpearl'))
		.itemOutputs(Item.of('1x terramity:cosmilite_ingot'))
		.duration(1200)
		.EUt(480)
	
	event.recipes.gtceu.twilight_awakening_chamber_mk2('conductite')
		.notConsumable(Item.of('1x kubejs:hostile_sample_2'))
		.itemInputs(Item.of('4x terramity:iridium'))
		.itemInputs(Item.of('1x terramity:black_matter'))
		.itemInputs(Item.of('4x #gtceu:circuits/lv'))
		.itemOutputs(Item.of('1x terramity:conductite'))
		.duration(1200)
		.EUt(1024)
	
	event.recipes.gtceu.twilight_awakening_chamber_mk2('void_alloy')
		.notConsumable(Item.of('1x kubejs:hostile_sample_2'))
		.itemInputs(Item.of('4x terramity:iridium'))
		.itemInputs(Item.of('1x terramity:black_matter'))
		.itemInputs(Item.of('4x terramity:empty_essence'))
		.itemOutputs(Item.of('1x terramity:void_alloy'))
		.duration(1200)
		.EUt(1024)
	
	event.recipes.gtceu.twilight_awakening_chamber_mk2('hellspec')
		.notConsumable(Item.of('1x kubejs:hostile_sample_2'))
		.itemInputs(Item.of('4x terramity:iridium'))
		.itemInputs(Item.of('1x terramity:firey_blood'))
		.itemInputs(Item.of('4x terramity:cthonic_crystal'))
		.itemOutputs(Item.of('1x terramity:chthonic_crystal'))
		.duration(1200)
		.EUt(1024)
	

})
