StartupEvents.registry('item', e => {
  e.create('cow_model_1')
  e.create('cow_model_2')
  e.create('cow_model_3')
  e.create('cow_model_4')
  e.create('cow_model_5')
  e.create('universal_cow_model')
  e.create('generic_bio_sample')
  e.create('hostile_bio_sample')
  e.create('earth_sample')
  e.create('star_casing_01')
  e.create('nether_sample')
  e.create('crushed_andesite')
  e.create('star_casing_02')
  e.create('blank_shard')
  e.create('raw_meat_glob')
  e.create('sterile_meat')
	
  e.create('hostile_sample_1')
  e.create('hostile_sample_2')

  e.create('wither_skeleton_model_1')
  e.create('shulker_model_1')
  e.create('enderman_model_1')
  e.create('blaze_model_1')
  e.create('phantom_model_1')
  e.create('slime_model_1')
  e.create('spider_model_1')
  e.create('magma_model_1')
  e.create('skeleton_model_1')
  e.create('ghast_model_1')
  e.create('creeper_model_1')
  e.create('zombie_model_1')

  e.create('warden_model_1')
  e.create('gaia_model_1')
  e.create('leviathan_model_1')
  e.create('amethyst_crab_model_1')
  e.create('ancient_remnant_model_1')
  e.create('harbinger_model_1')
  e.create('maledictus_model_1')
  e.create('ender_guardian_model_1')
  e.create('ignis_model_1')

  e.create('shulker_model_2')
  e.create('enderman_model_2')
  e.create('blaze_model_2')
  e.create('phantom_model_2')
  e.create('slime_model_2')
  e.create('spider_model_2')
  e.create('magma_model_2')
  e.create('skeleton_model_2')	
  e.create('ghast_model_2')
  e.create('creeper_model_2')
  e.create('zombie_model_2')

  e.create('warden_model_2')
  e.create('gaia_model_2')
  e.create('leviathan_model_2')
  e.create('amethyst_crab_model_2')
  e.create('ancient_remnant_model_2')
  e.create('harbinger_model_2')
  e.create('maledictus_model_2')
  e.create('ender_guardian_model_2')
  e.create('ignis_model_2')

  e.create('sheep_model_1')
  e.create('chicken_model_1')
  e.create('pig_model_1')
  e.create('squid_model_1')
  e.create('rabbit_model_1')
  e.create('fish_model_1')
  e.create('axolotl_model_1')
  e.create('bee_model_1')
  e.create('snow_golem_model_1')

  e.create('sheep_model_2')
  e.create('chicken_model_2')
  e.create('pig_model_2')
  e.create('squid_model_2')
  e.create('rabbit_model_2')
  e.create('fish_model_2')
  e.create('axolotl_model_2')
  e.create('bee_model_2')
  e.create('snow_golem_model_2')

  e.create('sheep_model_3')
  e.create('chicken_model_3')
  e.create('pig_model_3')
  e.create('squid_model_3')
  e.create('rabbit_model_3')
  e.create('fish_model_3')
  e.create('axolotl_model_3')
  e.create('bee_model_3')
  e.create('snow_golem_model_3')

  
  e.create('warden_model_3')
  e.create('gaia_model_3')
  e.create('leviathan_model_3')
  e.create('amethyst_crab_model_3')
  e.create('ancient_remnant_model_3')
  e.create('harbinger_model_3')
  e.create('maledictus_model_3')
  e.create('ender_guardian_model_3')
  e.create('ignis_model_3')

  e.create('life_sample_1')
  e.create('life_sample_2')
  e.create('life_sample_3')
  e.create('life_sample_4')

	
})