StartupEvents.registry('item', e => {
  e.create('mystical_flowers_1')
  e.create('carrots_1')
  e.create('potatoes_1')
  e.create('wheat_1')
  e.create('sourceberries_1')
  e.create('glowberries_1')
  e.create('moss_1')
  e.create('trees_1')
  e.create('chorus_fruit_1')
  e.create('kelp_1')
  e.create('pumpkin_seeds_1')
  e.create('cactus_1')
  e.create('plant_sample_1')

  e.create('mystical_flowers_2')
  e.create('carrots_2')
  e.create('potatoes_2')
  e.create('wheat_2')
  e.create('sourceberries_2')
  e.create('glowberries_2')
  e.create('moss_2')
  e.create('trees_2')
  e.create('chorus_fruit_2')
  e.create('kelp_2')
  e.create('pumpkin_seeds_2')
  e.create('cactus_2')
  e.create('plant_sample_2')

})