JEIEvents.hideItems(event => {
  event.hide('gtceu:andesite_alloy_ingot')
  event.hide('ad_astra:hammer')
  event.hide('ad_astra:compressor')
  event.hide('ad_astra:coal_generator')

  event.hide('gtceu:ulv_dna_fabricator')
  event.hide('mekanism:block_charcoal')
  event.hide('mekanism:dust_charcoal')
  event.hide('thermal:charcoal_block')
  event.hide('thermal:machine_pyrolyzer')
  event.hide('thermal:dynamo_stirling')
  event.hide('gtceu:brittle_charcoal')
  event.hide('gtceu:charcoal_pile_igniter')
  event.hide('gtceu:firebrick')
  event.hide('ad_astra:compressor' )
  event.hide('ad_astra:coal_generator' )
  event.hide('thermal:machine_furnace' )
  event.hide('thermal:machine_sawmill' )
  event.hide('thermal:machine_pulverizer' )
  event.hide('thermal:machine_smelter' )
  event.hide('thermal:machine_insolator' )
  event.hide('thermal:machine_sawmill' )
  event.hide('thermal:machine_centrifuge' )
  event.hide('thermal:machine_press' )
  event.hide('thermal:machine_crucible' )
  event.hide('thermal:machine_chiller' )
  event.hide('thermal:machine_refinery' )
  event.hide('thermal:machine_bottler' )
  event.hide('thermal:machine_brewer' )
  event.hide('thermal:machine_crystallizer' )
  event.hide('thermal:machine_crafter' )
  event.hide('thermal:device_rock_gen' )
  event.hide('thermal:device_tree_extractor' )
  event.hide('thermal:device_fisher' )
  event.hide('thermal:device_composter' )
  event.hide('thermal:device_water_gen' )
  event.hide('thermal:dynamo_compression' )
  event.hide('thermal:dynamo_magmatic' )
  event.hide('thermal:dynamo_numismatic' )
  event.hide('thermal:dynamo_lapidary' )
  event.hide('thermal:dynamo_disenchantment' )
  event.hide('thermal:dynamo_gourmand' )
  event.hide('gtceu:firebrick' )
  event.hide('create:brass_ingot' )
  event.hide('create:brass_nugget' )
  event.hide('create:brass_sheet' )

})

ClientEvents.lang('en_us', event => {
  event.renameBlock('create:copper_casing', 'Cupronickel Casing')
  event.renameBlock('create:copper_valve_handle', 'Cupronickel Valve Handle')
})