ServerEvents.recipes(event => {
	event.recipes.gtceu.animal_pen('cow_1')
		.notConsumable(Item.of('1x kubejs:cow_model_1'))
		.itemInputs(Item.of('8x minecraft:wheat'))
		.itemOutputs(Item.of('1x minecraft:leather'))
		.itemOutputs(Item.of('1x minecraft:beef'))
		.outputFluids(Fluid.of('minecraft:milk', 1000))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(24)
	
	event.recipes.gtceu.animal_pen('cow_2')
		.notConsumable(Item.of('1x kubejs:cow_model_2'))
		.itemInputs(Item.of('64x minecraft:wheat'))
		.itemOutputs(Item.of('16x minecraft:leather'))
		.itemOutputs(Item.of('16x minecraft:beef'))
		.outputFluids(Fluid.of('minecraft:milk', 8000))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(92)
	event.recipes.gtceu.animal_pen('squid_1')
		.notConsumable(Item.of('1x kubejs:squid_model_1'))
		.itemInputs(Item.of('8x #minecraft:fishes'))
		.itemOutputs(Item.of('1x minecraft:glow_ink_sac'))
		.itemOutputs(Item.of('1x minecraft:ink_sac'))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(24)	

	event.recipes.gtceu.animal_pen('sheep_1')
		.notConsumable(Item.of('1x kubejs:sheep_model_1'))
		.itemInputs(Item.of('8x minecraft:wheat'))
		.itemOutputs(Item.of('2x minecraft:wool'))
		.itemOutputs(Item.of('1x minecraft:mutton'))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(24)
	
	event.recipes.gtceu.animal_pen('pig_1')
		.notConsumable(Item.of('1x kubejs:pig_model_1'))
		.itemInputs(Item.of('8x minecraft:carrot'))
		.itemOutputs(Item.of('1x minecraft:porkchop'))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(24)
	
	event.recipes.gtceu.animal_pen('chicken_1')
		.notConsumable(Item.of('1x kubejs:chicken_model_1'))
		.itemInputs(Item.of('8x #forge:seeds'))
		.itemOutputs(Item.of('1x minecraft:chicken'))
		.itemOutputs(Item.of('1x minecraft:feather'))
		.itemOutputs(Item.of('1x minecraft:egg'))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(24)
	
	event.recipes.gtceu.animal_pen('bee_1')
		.notConsumable(Item.of('1x kubejs:bee_model_1'))
		.itemInputs(Item.of('8x #minecraft:flowers'))
		.itemOutputs(Item.of('1x minecraft:honeycomb'))
		.outputFluids(Fluid.of('create:honey', 1000))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(24)	
	event.recipes.gtceu.animal_pen('rabbit_1')
		.notConsumable(Item.of('1x kubejs:rabbit_model_1'))
		.itemInputs(Item.of('8x minecraft:carrot'))
		.itemOutputs(Item.of('1x minecraft:rabbit'))
		.itemOutputs(Item.of('4x minecraft:rabbit_hide'))
		.itemOutputs(Item.of('1x minecraft:rabbit_foot'))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(24)
	event.recipes.gtceu.animal_pen('fish_1')
		.notConsumable(Item.of('1x kubejs:fish_model_1'))
		.itemInputs(Item.of('8x #forge:seeds'))
		.itemOutputs(Item.of('2x minecraft:salmon'))
		.itemOutputs(Item.of('1x minecraft:bone'))
		.outputFluids(Fluid.of('gtceu:biomass',10))

		.duration(1200)
		.EUt(24)
})
