ServerEvents.recipes(event => {
	event.recipes.gtceu.breeding_chamber('cow_1')
		.notConsumable(Item.of('2x kubejs:cow_model_2'))
		.itemInputs(Item.of('2x kubejs:wheat_1'))
		.inputFluids(Fluid.of('kubejs:taiga_essence',144))
		.itemOutputs(Item.of('1x kubejs:cow_model_1'))
		.duration(2400)
		.EUt(480)
	event.recipes.gtceu.breeding_chamber('sheep_1')
		.notConsumable(Item.of('2x kubejs:sheep_model_2'))
		.itemInputs(Item.of('2x kubejs:wheat_1'))
		.inputFluids(Fluid.of('kubejs:taiga_essence',144))
		.itemOutputs(Item.of('1x kubejs:cow_model_1'))
		.duration(2400)
		.EUt(480)
	event.recipes.gtceu.breeding_chamber('chicken_1')
		.notConsumable(Item.of('2x kubejs:chicken_model_2'))
		.itemInputs(Item.of('2x #forge:seeds'))
		.inputFluids(Fluid.of('kubejs:sky_essence',144))
		.itemOutputs(Item.of('1x kubejs:chicken_model_1'))
		.duration(2400)
		.EUt(480)
	event.recipes.gtceu.breeding_chamber('pig_1')
		.notConsumable(Item.of('2x kubejs:pig_model_2'))
		.itemInputs(Item.of('2x kubejs:carrots_1'))
		.inputFluids(Fluid.of('kubejs:earth_essence',144))
		.itemOutputs(Item.of('1x kubejs:pig_model_1'))
		.duration(2400)
		.EUt(480)
	event.recipes.gtceu.breeding_chamber('fish_1')
		.notConsumable(Item.of('2x kubejs:fish_model_2'))
		.itemInputs(Item.of('2x #forge:seeds'))
		.inputFluids(Fluid.of('kubejs:ocean_essence',144))
		.inputFluids(Fluid.of('kubejs:fish_oil',144))
		.itemOutputs(Item.of('1x kubejs:fish_model_1'))
		.duration(2400)
		.EUt(480)
	event.recipes.gtceu.breeding_chamber('rabbit_1')
		.notConsumable(Item.of('2x kubejs:rabbit_model_2'))
		.itemInputs(Item.of('2x kubejs:carrots_1'))
		.inputFluids(Fluid.of('kubejs:desert_essence',144))
		.itemOutputs(Item.of('1x kubejs:rabbit_model_1'))
		.duration(2400)
		.EUt(480)
	event.recipes.gtceu.breeding_chamber('squid_1')
		.notConsumable(Item.of('2x kubejs:squid_model_2'))
		.itemInputs(Item.of('2x kubejs:fish_model_1'))
		.inputFluids(Fluid.of('kubejs:ocean_essence',144))
		.itemOutputs(Item.of('1x kubejs:squid_model_1'))
		.duration(2400)
		.EUt(480)
	event.recipes.gtceu.breeding_chamber('axolotl_1')
		.notConsumable(Item.of('2x kubejs:axolotl_model_2'))
		.itemInputs(Item.of('2x kubejs:moss_1'))
		.inputFluids(Fluid.of('kubejs:earth_essence',144))
		.itemOutputs(Item.of('1x kubejs:axolotl_model_1'))
		.duration(2400)
		.EUt(480)
	event.recipes.gtceu.breeding_chamber('bee_1')
		.notConsumable(Item.of('2x kubejs:bee_model_2'))
		.itemInputs(Item.of('2x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:sky_essence',144))
		.itemOutputs(Item.of('1x kubejs:bee_model_1'))
		.duration(2400)
		.EUt(480)
	
	event.recipes.gtceu.breeding_chamber('cow_2')
		.notConsumable(Item.of('2x kubejs:cow_model_3'))
		.itemInputs(Item.of('2x kubejs:wheat_2'))
		.inputFluids(Fluid.of('kubejs:taiga_essence',1000))
		.itemOutputs(Item.of('1x kubejs:cow_model_2'))
		.duration(2400)
		.EUt(1280)
})
