ServerEvents.recipes(event => {
	event.recipes.gtceu.animal_pen('wither_skeleton_1')
		.notConsumable(Item.of('1x kubejs:wither_skeleton_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:wither_skeleton_skull'))
		.duration(200)
		.EUt(128)

    event.recipes.gtceu.animal_pen('blaze_1')
		.notConsumable(Item.of('1x kubejs:blaze_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:blaze_rod'))
		.duration(200)
		.EUt(128)

    event.recipes.gtceu.animal_pen('slime_1')
		.notConsumable(Item.of('1x kubejs:slime_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:slime_ball'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('magma_cube_1')
		.notConsumable(Item.of('1x kubejs:magma_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:magma_cream'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('shulker_1')
		.notConsumable(Item.of('1x kubejs:shulker_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:shulker_shell'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('enderman_1')
		.notConsumable(Item.of('1x kubejs:enderman_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:ender_pearl'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('phantom_1')
		.notConsumable(Item.of('1x kubejs:phantom_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:phantom_membrane'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('spider_1')
		.notConsumable(Item.of('1x kubejs:spider_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:string'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('skeleton_1')
		.notConsumable(Item.of('1x kubejs:skeleton_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:bone'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('ghast_1')
		.notConsumable(Item.of('1x kubejs:ghast_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:ghast_tear'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('creeper_1')
		.notConsumable(Item.of('1x kubejs:creeper_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:gunpowder'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('zombie_1')
		.notConsumable(Item.of('1x kubejs:zombie_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:rotten_flesh'))
		.duration(200)
		.EUt(128)
})