ServerEvents.recipes(event => {
	event.recipes.gtceu.hostile_containment_unit('wither_skeleton_1')
		.notConsumable(Item.of('1x kubejs:wither_skeleton_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:wither_skeleton_skull'))
		.duration(200)
		.EUt(128)

    event.recipes.gtceu.hostile_containment_unit('blaze_1')
		.notConsumable(Item.of('1x kubejs:blaze_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:blaze_rod'))
		.duration(200)
		.EUt(128)

    event.recipes.gtceu.hostile_containment_unit('slime_1')
		.notConsumable(Item.of('1x kubejs:slime_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:slime_ball'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.animal_pen('magma_cube_1')
		.notConsumable(Item.of('1x kubejs:magma_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:magma_cream'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.hostile_containment_unit('shulker_1')
		.notConsumable(Item.of('1x kubejs:shulker_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:shulker_shell'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.hostile_containment_unit('enderman_1')
		.notConsumable(Item.of('1x kubejs:enderman_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:ender_pearl'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.hostile_containment_unit('phantom_1')
		.notConsumable(Item.of('1x kubejs:phantom_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:phantom_membrane'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.hostile_containment_unit('spider_1')
		.notConsumable(Item.of('1x kubejs:spider_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:string'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.hostile_containment_unit('skeleton_1')
		.notConsumable(Item.of('1x kubejs:skeleton_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:bone'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.hostile_containment_unit('ghast_1')
		.notConsumable(Item.of('1x kubejs:ghast_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:ghast_tear'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.hostile_containment_unit('creeper_1')
		.notConsumable(Item.of('1x kubejs:creeper_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:gunpowder'))
		.duration(200)
		.EUt(128)

        event.recipes.gtceu.hostile_containment_unit('zombie_1')
		.notConsumable(Item.of('1x kubejs:zombie_model_1'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('1x minecraft:rotten_flesh'))
		.duration(200)
		.EUt(128)


        event.recipes.gtceu.hostile_containment_unit('ur-ghast')
		.notConsumable(Item.of('1x twilightforest:ur_ghast_trophy'))
		.itemInputs(Item.of('1x minecraft:ghast_tear'))
		.itemInputs(Item.of('1x kubejs:sky_dust'))
		.inputFluids(Fluid.of('kubejs:living_matter', 16))
		.itemOutputs(Item.of('8x twilightforest:carminite'))
		.duration(200)
		.EUt(480)

        event.recipes.gtceu.hostile_containment_unit('lich')
		.notConsumable(Item.of('1x twilightforest:lich_trophy'))
		.itemInputs(Item.of('1x minecraft:bone_meal'))
		.itemInputs(Item.of('1x kubejs:skeleton_model_1'))
		.inputFluids(Fluid.of('gtceu:carbon', 144))
		.itemOutputs(Item.of('8x minecraft:gold_ore'))
		.duration(200)
		.EUt(480)

        event.recipes.gtceu.hostile_containment_unit('naga')
		.notConsumable(Item.of('1x twilightforest:naga_trophy'))
		.itemInputs(Item.of('1x gtceu:coke_gem'))
		.itemInputs(Item.of('1x #minecraft:leaves'))
		.itemInputs(Item.of('1x kubejs:dense_insulator_sheet'))
		.inputFluids(Fluid.of('gtceu:carbon_dioxide', 144))
		.itemOutputs(Item.of('8x twilightforest:naga_scale'))
		.duration(200)
		.EUt(480)

		event.recipes.gtceu.hostile_containment_unit('snow_queen')
		.notConsumable(Item.of('1x twilightforest:snow_queen_trophy'))
		.itemInputs(Item.of('1x minecraft:blue_ice'))
		.itemInputs(Item.of('1x gtceu:phenolic_circuit_board'))
		.itemInputs(Item.of('1x minecraft:gold_ingot'))
		.itemOutputs(Item.of('8x twilightforest:aurora_block'))
		.duration(200)
		.EUt(480)

		event.recipes.gtceu.hostile_containment_unit('hydra')
		.notConsumable(Item.of('1x twilightforest:hydra_trophy'))
		.itemInputs(Item.of('1x minecraft:dragon_breath'))
		.itemInputs(Item.of('1x minecraft:phantom_membrane'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 144))
		.itemOutputs(Item.of('8x twilightforest:fiery_blood'))
		.duration(200)
		.EUt(480)

})