ServerEvents.recipes(event => {
	event.recipes.gtceu.crop_simulator('wheat_seeds_0')
		.notConsumable(Item.of('1x minecraft:wheat_seeds'))
		.inputFluids(Fluid.of('minecraft:water', 100))
		.itemOutputs(Item.of('1x minecraft:wheat'))
		.chancedOutput('1x minecraft:wheat_seeds', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('wheat_seeds_1')
		.itemInputs(Item.of('1x kubejs:wheat_seeds_mk1'))
		.inputFluids(Fluid.of('minecraft:water', 100))
		.itemOutputs(Item.of('8x minecraft:wheat'))
		.chancedOutput('1x kubejs:wheat_seeds_mk1', 9000, 0)
		.chancedOutput('1x kubejs:wheat_seeds_mk1', 500, 500)
		.duration(12000)
		.EUt(32)	

	event.recipes.gtceu.crop_simulator('poppy_0')
		.notConsumable(Item.of('1x minecraft:poppy'))
		.inputFluids(Fluid.of('minecraft:water', 100))
		.itemOutputs(Item.of('1x minecraft:poppy'))
		.chancedOutput('1x minecraft:poppy', 5000, 500)
		.duration(12000)
		.EUt(8)	

	event.recipes.gtceu.crop_simulator('mystical_flowers_1_white')
		.circuit(1)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:white_petal'))
		.chancedOutput('1x botania:white_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_black')
		.circuit(2)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:black_petal'))
		.chancedOutput('1x botania:black_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_light_gray')
		.circuit(3)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:light_gray_petal'))
		.chancedOutput('1x botania:light_gray_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_gray')
		.circuit(4)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:gray_petal'))
		.chancedOutput('1x botania:gray_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_brown')
		.circuit(5)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:brown_petal'))
		.chancedOutput('1x botania:brown_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_red')
		.circuit(6)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:red_petal'))
		.chancedOutput('1x botania:red_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_orange')
		.circuit(7)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:orange_petal'))
		.chancedOutput('1x botania:orange_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_yellow')
		.circuit(8)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:yellow_petal'))
		.chancedOutput('1x botania:yellow_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
		event.recipes.gtceu.crop_simulator('mystical_flowers_1_lime')
		.circuit(9)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:lime_petal'))
		.chancedOutput('1x botania:lime_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_green')
		.circuit(10)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:green_petal'))
		.chancedOutput('1x botania:green_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_light_blue')
		.circuit(11)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:light_blue_petal'))
		.chancedOutput('1x botania:light_blue_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_cyan')
		.circuit(12)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:cyan_petal'))
		.chancedOutput('1x botania:cyan_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_blue')
		.circuit(13)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:blue_petal'))
		.chancedOutput('1x botania:blue_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_purple')
		.circuit(14)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:purple_petal'))
		.chancedOutput('1x botania:purple_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_magenta')
		.circuit(15)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:magenta_petal'))
		.chancedOutput('1x botania:magenta_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
	event.recipes.gtceu.crop_simulator('mystical_flowers_1_pink')
		.circuit(16)
		.notConsumable(Item.of('1x kubejs:mystical_flowers_1'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 100))
		.itemOutputs(Item.of('1x botania:pink_petal'))
		.chancedOutput('1x botania:pink_petal', 5000, 500)
		.duration(12000)
		.EUt(8)	
})
