ServerEvents.recipes(event => {
	event.recipes.gtceu.resource_combinator('mystical_flowers_1')
		.itemInputs(Item.of('64x botania:red_petal'))
		.itemInputs(Item.of('64x botania:orange_petal'))
		.itemInputs(Item.of('64x botania:yellow_petal'))
		.itemInputs(Item.of('64x botania:lime_petal'))
		.itemInputs(Item.of('64x botania:green_petal'))
		.itemInputs(Item.of('64x botania:light_blue_petal'))
		.itemInputs(Item.of('64x botania:cyan_petal'))
		.itemInputs(Item.of('64x botania:blue_petal'))
		.itemInputs(Item.of('64x botania:purple_petal'))
		.itemInputs(Item.of('64x botania:magenta_petal'))
		.itemInputs(Item.of('64x botania:pink_petal'))
		.itemInputs(Item.of('64x botania:brown_petal'))
		.itemInputs(Item.of('64x botania:black_petal'))
		.itemInputs(Item.of('64x botania:gray_petal'))
		.itemInputs(Item.of('64x botania:light_gray_petal'))
		.itemInputs(Item.of('64x botania:white_petal'))
		.inputFluids(Fluid.of('kubejs:manafloraethylene', 16000))
		.itemOutputs(Item.of('1x kubejs:mystical_flowers_1'))
		.duration(2000)
		.EUt(480)	
	
		event.recipes.gtceu.resource_combinator('wheat_seeds_1')
		.itemInputs(Item.of('64x minecraft:wheat_seeds'))
		.inputFluids(Fluid.of('minecraft:water',1000))
		.chancedOutput('1x kubejs:wheat_seeds_mk1', 500, 500)
		.duration(1200)
		.EUt(32)
})