
ServerEvents.recipes(event => {

    event.recipes.gtceu.temperate_garden('wheat_0')
    .circuit(1)
    .itemInputs(Item.of('1x minecraft:wheat_seeds'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:wheat'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('wheat_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:wheat_1'))
    .itemInputs(Item.of('1x minecraft:wheat_seeds'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('4x minecraft:wheat'))
    .chancedOutput('1x kubejs:wheat_1',2000,500)
    .duration(4000)
    .EUt(244)	
    event.recipes.gtceu.temperate_garden('wheat_1_with_seed')
    .circuit(3)

    .notConsumable(Item.of('1x kubejs:wheat_1'))
    .itemInputs(Item.of('1x kubejs:wheat_seeds_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .inputFluids(Fluid.of('kubejs:growth_medium', 72))
    .itemOutputs('2x kubejs:wheat_1')
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('wheat_2_with_seed')
    .circuit(4)

    .notConsumable(Item.of('1x kubejs:wheat_2'))
    .itemInputs(Item.of('1x kubejs:wheat_seeds_2'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 144))
    .inputFluids(Fluid.of('kubejs:growth_medium', 72))
    .itemOutputs('2x kubejs:wheat_2')
    .duration(1200)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('pumpkin_0')
    .circuit(1)
    .itemInputs(Item.of('1x minecraft:pumpkin_seeds'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:pumpkin'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('pumpkin_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:pumpkin_1'))
    .itemInputs(Item.of('1x minecraft:pumpkin_seeds'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('4x minecraft:pumpkin'))
    .chancedOutput('1x kubejs:pumpkin_1',2000,500)
    .duration(4000)
    .EUt(244)	
    event.recipes.gtceu.temperate_garden('pumpkin_1_with_seed')
    .circuit(3)

    .notConsumable(Item.of('1x kubejs:pumpkin_1'))
    .itemInputs(Item.of('1x kubejs:pumpkin_seeds_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .inputFluids(Fluid.of('kubejs:growth_medium', 72))
    .itemOutputs('1x kubejs:pumpkin_1')
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('pumpkin_2_with_seed')
    .circuit(4)

    .notConsumable(Item.of('1x kubejs:pumpkin_2'))
    .itemInputs(Item.of('1x kubejs:pumpkin_seeds_2'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 144))
    .inputFluids(Fluid.of('kubejs:growth_medium', 72))
    .itemOutputs('2x kubejs:pumpkin_2')
    .duration(1200)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('carrots_0')
    .circuit(1)
    .itemInputs(Item.of('1x minecraft:carrot'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:carrot'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('carrots_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:carrots_1'))
    .itemInputs(Item.of('1x kubejs:carrots_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:carrots_1'))
    .chancedOutput('1x kubejs:carrots_1',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('carrots_2')
    .circuit(3)
    .notConsumable(Item.of('1x kubejs:carrots_2'))
    .itemInputs(Item.of('1x kubejs:carrots_2'))
    .itemInputs(Item.of('1x gtceu:fertilizer'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:carrots_2'))
    .chancedOutput('1x kubejs:carrots_2',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('potatoes_0')
    .circuit(1)
    .itemInputs(Item.of('1x minecraft:potato'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:potato'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('potatoes_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:potatoes_1'))
    .itemInputs(Item.of('1x kubejs:potatoes_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:potatoes_1'))
    .chancedOutput('1x kubejs:potatoes_1',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('potatoes_2')
    .circuit(3)
    .notConsumable(Item.of('1x kubejs:potatoes_2'))
    .itemInputs(Item.of('1x kubejs:potatoes_2'))
    .itemInputs(Item.of('1x gtceu:fertilizer'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:potatoes_2'))
    .chancedOutput('1x kubejs:potatoes_2',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('kelp_0')
    .circuit(1)
    .itemInputs(Item.of('1x minecraft:kelp'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:kelp'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('kelp_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:kelp_1'))
    .itemInputs(Item.of('1x kubejs:kelp_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:kelp_1'))
    .chancedOutput('1x kubejs:kelp_1',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('kelp_2')
    .circuit(3)
    .notConsumable(Item.of('1x kubejs:kelp_2'))
    .itemInputs(Item.of('1x kubejs:kelp_2'))
    .itemInputs(Item.of('1x gtceu:fertilizer'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:kelp_2'))
    .chancedOutput('1x kubejs:kelp_2',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('moss_0')
    .circuit(1)
    .itemInputs(Item.of('1x minecraft:moss_block'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:moss_block'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('moss_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:moss_1'))
    .itemInputs(Item.of('1x kubejs:moss_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:moss_1'))
    .chancedOutput('1x kubejs:moss_1',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('moss_2')
    .circuit(3)
    .notConsumable(Item.of('1x kubejs:moss_2'))
    .itemInputs(Item.of('1x kubejs:moss_2'))
    .itemInputs(Item.of('1x gtceu:fertilizer'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:moss_2'))
    .chancedOutput('1x kubejs:moss_2',2000,500)
    .duration(4000)
    .EUt(244)	
    event.recipes.gtceu.temperate_garden('chorus_fruit_0')
    .circuit(1)
    .itemInputs(Item.of('1x minecraft:chorus_fruit'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:chorus_fruit'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('chorus_fruit_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:chorus_fruit_1'))
    .itemInputs(Item.of('1x kubejs:chorus_fruit_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:chorus_fruit_1'))
    .chancedOutput('1x kubejs:chorus_fruit_1',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('chorus_fruit_2')
    .circuit(3)
    .notConsumable(Item.of('1x kubejs:chorus_fruit_2'))
    .itemInputs(Item.of('1x kubejs:chorus_fruit_2'))
    .itemInputs(Item.of('1x gtceu:fertilizer'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:chorus_fruit_2'))
    .chancedOutput('1x kubejs:chorus_fruit_2',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('sourceberries_0')
    .circuit(1)
    .itemInputs(Item.of('1x ars_nouveau:sourceberry_bush'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:sourceberry_bush'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('sourceberries_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:sourceberries_1'))
    .itemInputs(Item.of('1x kubejs:sourceberries_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:sourceberries_1'))
    .chancedOutput('1x kubejs:sourceberries_1',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('sourceberries_2')
    .circuit(3)
    .notConsumable(Item.of('1x kubejs:sourceberries_2'))
    .itemInputs(Item.of('1x kubejs:sourceberries_2'))
    .itemInputs(Item.of('1x gtceu:fertilizer'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:sourceberries_2'))
    .chancedOutput('1x kubejs:sourceberries_2',2000,500)
    .duration(4000)
    .EUt(244)

    event.recipes.gtceu.temperate_garden('glowberries_0')
    .circuit(1)
    .itemInputs(Item.of('1x minecraft:glowberries'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 36))
    .itemOutputs(Item.of('2x minecraft:glowberries'))
    .duration(12000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('glowberries_1')
    .circuit(2)

    .notConsumable(Item.of('1x kubejs:glowberries_1'))
    .itemInputs(Item.of('1x kubejs:glowberries_1'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:glowberries_1'))
    .chancedOutput('1x kubejs:glowberries_1',2000,500)
    .duration(4000)
    .EUt(244)	

    event.recipes.gtceu.temperate_garden('glowberries_2')
    .circuit(3)
    .notConsumable(Item.of('1x kubejs:glowberries_2'))
    .itemInputs(Item.of('1x kubejs:glowberries_2'))
    .itemInputs(Item.of('1x gtceu:fertilizer'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x kubejs:glowberries_2'))
    .chancedOutput('1x kubejs:glowberries_2',2000,500)
    .duration(4000)
    .EUt(244)

	
	
//mystical flowers
	   event.recipes.gtceu.temperate_garden('mystical_white')
    .circuit(0)
    .itemInputs(Item.of('1x botania:white_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:white_mystical_flower'))
    .duration(4000)
    .EUt(244)
   event.recipes.gtceu.temperate_garden('mystical_orange')
    .circuit(1)
    .itemInputs(Item.of('1x botania:orange_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:orange_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_magenta')
    .circuit(2)
    .itemInputs(Item.of('1x botania:magenta_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:magenta_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_light_blue')
    .circuit(3)
    .itemInputs(Item.of('1x botania:light_blue_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:light_blue_mystical_flower'))
    .duration(4000)
    .EUt(244)
   event.recipes.gtceu.temperate_garden('mystical_yellow')
    .circuit(4)
    .itemInputs(Item.of('1x botania:yellow_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:yellow_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_lime')
    .circuit(5)
    .itemInputs(Item.of('1x botania:lime_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:lime_mystical_flower'))
    .duration(4000)
    .EUt(244)
   event.recipes.gtceu.temperate_garden('mystical_pink')
    .circuit(6)
    .itemInputs(Item.of('1x botania:pink_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:pink_mystical_flower'))
    .duration(4000)
    .EUt(244)
   event.recipes.gtceu.temperate_garden('mystical_gray')
    .circuit(7)
    .itemInputs(Item.of('1x botania:gray_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:gray_mystical_flower'))
    .duration(4000)
    .EUt(244)
   event.recipes.gtceu.temperate_garden('mystical_light_gray')
    .circuit(8)
    .itemInputs(Item.of('1x botania:light_gray_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:light_gray_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_cyan')
    .circuit(9)
    .itemInputs(Item.of('1x botania:cyan_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:cyan_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_purple')
    .circuit(10)
    .itemInputs(Item.of('1x botania:purple_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:purple_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_blue')
    .circuit(11)
    .itemInputs(Item.of('1x botania:blue_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:blue_mystical_flower'))
    .duration(4000)
    .EUt(244)
   event.recipes.gtceu.temperate_garden('mystical_brown')
    .circuit(12)
    .itemInputs(Item.of('1x botania:brown_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:brown_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_green')
    .circuit(13)
    .itemInputs(Item.of('1x botania:green_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:green_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_red')
    .circuit(14)
    .itemInputs(Item.of('1x botania:red_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:red_mystical_flower'))
    .duration(4000)
    .EUt(244)
    event.recipes.gtceu.temperate_garden('mystical_black')
    .circuit(15)
    .itemInputs(Item.of('1x botania:black_petal'))
    .itemInputs(Item.of('1x minecraft:bone_meal'))
    .inputFluids(Fluid.of('gtceu:fermented_biomass', 72))
    .itemOutputs(Item.of('1x botania:black_mystical_flower'))
    .duration(4000)
    .EUt(244)

})